[package]
name = "animecix"
version = "1.2.4"
edition = "2021"
description = "Türkçe anime izleme uygulaması (GTK4/libadwaita + mpv)"
homepage = "https://github.com/veilzon/animecix-linux"
repository = "https://github.com/veilzon/animecix-linux"
license = "MIT"

[dependencies]
gtk = { package = "gtk4", version = "0.8", features = ["v4_8"] }
adw = { package = "libadwaita", version = "0.6", features = ["v1_2"] }
glib = "0.19"
gio = "0.19"
gdk-pixbuf = "0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zstd = "0.13"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "stream", "rustls-tls"] }
wreq = "=6.0.0-rc.31"
wreq-util = "=3.0.0-rc.14"
futures = "0.3"
tokio = { version = "1", features = ["rt", "net", "time"] }
libc = "0.2.189"
hmac = "0.12"
sha2 = "0.10"
aes-gcm = "0.10"

[profile.release]
lto = true
